guidelines:
	pdflatex guidelines
	pdflatex guidelines
	bibtex guidelines
	makeindex guidelines
	makeglossaries guidelines
	pdflatex guidelines
	pdflatex guidelines
clean:
	rm *.log *.aux *.dvi *.lof *.lot *.bit *.idx *.glo *.bbl *.bcf *.ilg *.toc *.ind *.out *.blg *.fdb_latexmk *.fls *.thm *.gz *.pdf
